### ISSUE TITLE
[BUG]: Error on trying to join a server without visiting localhost:3000 first

### ISSUE THREAD

**Issue by prakartigoel24** [Univibe-majorproject/UniVibe#37]
## Bug Report

**Describe the bug**
When the server invite link is pasted in the url bar of the browser where the user has not visited localhost:3000 before to sign in (user not logged in) then it gives the following error. 

**To Reproduce**
1. Get the invite URL for a server.
2. Paste the URL into another browser where you are not logged in to the application or haven't created an account yet by visiting localhost:3000.
3. Choose the sign in using google option and choose an account which is not joined in the server the invite link is for.
4. An error message (image below) is shown instead of joining and redirecting to the server automatically. 
5. *If you will visit localhost:3000 first and sign in using google and then paste the invite link in the url bar then the server will be joined successfully.*

**Expected Behavior:**
1. Upon pasting the invite link for the server in the url bar of the browser.
2. The user should successfully join the server and be redirected to the server page after signing in using google account.

**Screenshots**
![image](https://github.com/Univibe-majorproject/UniVibe/assets/65300982/095bd35f-6d97-4259-875f-b1243cae199a)

**Comment by SuperiorSam22** [comment]
I'm not able to reproduce this issue. I tried to do it in brave and MS edge. I'm being redirected to Sign In page.
Steps followed -
1. Opened the local host in chrome 
2. Clicked invite people - copied the link 
3. Pasted the link in Brave and MS Edge browser 
4.
